### ISSUE TITLE
homepage link broken in Melpa

### ISSUE THREAD

**Issue by tjaartvdwalt** [Malabarba/conkeror-minor-mode#5]
A small issue I found when installing the package from Melpa, is that the Homepage link is broken.
It reads:
http://github.com/BruceConnor/conkeror-minor-mode

but it should be:
http://github.com/Bruce-Connor/conkeror-minor-mode

**Comment by Bruce-Connor** [comment]
Oops. Thanks for filing this. I'll fix as soon as I can.

**Comment by Malabarba** [comment]
Fixed.
